import ReactECharts from "echarts-for-react";
import type { ActiveJob } from "@/bindings/ActiveJob";
import type { ProcessInfo } from "@/bindings/ProcessInfo";

interface CpuSunburstChartProps {
  jobs: ActiveJob[];
  runColors?: Record<string, string>;
}

export function CpuSunburstChart({
  jobs,
  runColors = {},
}: CpuSunburstChartProps) {
  const data = jobs
    .map((job) => {
      const color = runColors[job.id] || "#3b82f6";

      const mapProcess = (proc: ProcessInfo, depth: number): any => {
        // Set a minimum threshold so tiny background threads don't crowd the visual mapping,
        // but retain parent process hierarchy natively
        const selfCpu = Math.max(0.1, proc.cpu_usage);
        const children =
          proc.children
            ?.filter((c) => c.cpu_usage > 0.5 || c.children.length > 0)
            .map((c) => mapProcess(c, depth + 1)) || [];

        const nodeColor = depth === 0 ? color : undefined;

        if (children.length === 0) {
          return {
            name: proc.name,
            value: selfCpu,
            itemStyle: nodeColor ? { color: nodeColor } : undefined,
          };
        }

        const selfNode = {
          name: "Self",
          value: selfCpu,
        };

        return {
          name: proc.name,
          itemStyle: nodeColor ? { color: nodeColor } : undefined,
          children: [selfNode, ...children],
        };
      };

      return job.root_process
        ? mapProcess(job.root_process, 0)
        : {
            name: job.name,
            value: 0,
          };
    })
    .filter((d) => d.value > 0 || (d.children && d.children.length > 0));

  const option = {
    backgroundColor: "transparent",
    tooltip: {
      trigger: "item",
      formatter: (params: any) => {
        const title =
          params.name === "Self"
            ? params.treePathInfo[params.treePathInfo.length - 2].name +
              " (Self)"
            : params.name;
        return `${title}: ${params.value.toFixed(1)}% CPU`;
      },
      backgroundColor: "rgba(0,0,0,0.8)",
      borderColor: "#333",
      textStyle: { color: "#fff", fontSize: 12 },
    },
    series: {
      type: "sunburst",
      data: data,
      radius: ["15%", "90%"],
      sort: null, // Keep ordering generated by arrays
      itemStyle: {
        borderRadius: 3,
        borderWidth: 1.5,
        borderColor: "#080808",
      },
      label: {
        show: true,
        rotate: "radial",
        color: "#fff",
        fontSize: 10,
        fontWeight: 600,
        minAngle: 12,
        formatter: (params: any) => {
          if (params.name === "Self") return "";
          return params.name;
        },
      },
    },
  };

  return (
    <div className="w-full h-full flex flex-col bg-[#080808] border-r border-border/20">
      <div className="flex items-center px-3 py-1.5 border-b border-white/10 bg-zinc-950/80 shrink-0">
        <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">
          CPU Topography
        </span>
      </div>
      <div className="flex-1 w-full relative overflow-hidden">
        {data.length === 0 ? (
          <div className="absolute inset-0 flex items-center justify-center text-zinc-600 text-xs font-medium uppercase tracking-wider">
            No Telemetry
          </div>
        ) : (
          <ReactECharts
            option={option}
            style={{ height: "100%", width: "100%" }}
            opts={{ renderer: "canvas" }}
          />
        )}
      </div>
    </div>
  );
}
