version: '3.9'

services:
  tricked-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./runs:/app/runs
      - ./metrics.json:/app/metrics.json
      - ./GUMBEL_MUZERO_DOSSIER.md:/app/GUMBEL_MUZERO_DOSSIER.md
      - ./conf:/app/conf
    ports:
      - "8080:8080" # FastAPI
      - "8265:8265" # Ray Dashboard
    shm_size: "64gb"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - REDIS_HOST=redis
      - WANDB_BASE_URL=http://wandb-local:8080
      - WANDB_API_KEY=local-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
      - LIBTORCH_USE_PYTORCH=1
      - LIBTORCH_BYPASS_VERSION_CHECK=1
    depends_on:
      - redis
      - wandb-local
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  tricked-ui:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - BACKEND_HOST=tricked-backend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - tricked-backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  wandb-local:
    image: wandb/local
    ports:
      - "8081:8080"
    volumes:
      - wandb_data:/vol

volumes:
  wandb_data:
