// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "tricked.proto" (package "tricked", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// Configuration Models

/**
 * @generated from protobuf message tricked.HardwareConfig
 */
export interface HardwareConfig {
    /**
     * @generated from protobuf field: string device = 1
     */
    device: string;
    /**
     * @generated from protobuf field: int32 num_processes = 2
     */
    numProcesses: number;
    /**
     * @generated from protobuf field: string worker_device = 3
     */
    workerDevice: string;
    /**
     * @generated from protobuf field: int32 inference_batch_size_limit = 4
     */
    inferenceBatchSizeLimit: number;
    /**
     * @generated from protobuf field: int32 inference_timeout_ms = 5
     */
    inferenceTimeoutMs: number;
}
/**
 * @generated from protobuf message tricked.ArchitectureConfig
 */
export interface ArchitectureConfig {
    /**
     * @generated from protobuf field: int32 hidden_dimension_size = 1
     */
    hiddenDimensionSize: number;
    /**
     * @generated from protobuf field: int32 num_blocks = 2
     */
    numBlocks: number;
    /**
     * @generated from protobuf field: int32 value_support_size = 3
     */
    valueSupportSize: number;
    /**
     * @generated from protobuf field: int32 reward_support_size = 4
     */
    rewardSupportSize: number;
    /**
     * @generated from protobuf field: int32 spatial_channel_count = 5
     */
    spatialChannelCount: number;
    /**
     * @generated from protobuf field: int32 hole_predictor_dim = 6
     */
    holePredictorDim: number;
}
/**
 * @generated from protobuf message tricked.OptimizerConfig
 */
export interface OptimizerConfig {
    /**
     * @generated from protobuf field: int32 buffer_capacity_limit = 1
     */
    bufferCapacityLimit: number;
    /**
     * @generated from protobuf field: int32 train_batch_size = 2
     */
    trainBatchSize: number;
    /**
     * @generated from protobuf field: float discount_factor = 3
     */
    discountFactor: number;
    /**
     * @generated from protobuf field: float td_lambda = 4
     */
    tdLambda: number;
    /**
     * @generated from protobuf field: float weight_decay = 5
     */
    weightDecay: number;
    /**
     * @generated from protobuf field: float lr_init = 6
     */
    lrInit: number;
    /**
     * @generated from protobuf field: int32 unroll_steps = 7
     */
    unrollSteps: number;
    /**
     * @generated from protobuf field: int32 temporal_difference_steps = 8
     */
    temporalDifferenceSteps: number;
    /**
     * @generated from protobuf field: float reanalyze_ratio = 9
     */
    reanalyzeRatio: number;
    /**
     * @generated from protobuf field: int32 max_steps = 10
     */
    maxSteps: number;
    /**
     * @generated from protobuf field: optional float prioritized_replay_alpha = 11
     */
    prioritizedReplayAlpha?: number;
    /**
     * @generated from protobuf field: optional float prioritized_replay_beta = 12
     */
    prioritizedReplayBeta?: number;
}
/**
 * @generated from protobuf message tricked.MctsConfig
 */
export interface MctsConfig {
    /**
     * @generated from protobuf field: int32 simulations = 1
     */
    simulations: number;
    /**
     * @generated from protobuf field: int32 max_gumbel_k = 2
     */
    maxGumbelK: number;
    /**
     * @generated from protobuf field: float gumbel_scale = 3
     */
    gumbelScale: number;
}
/**
 * @generated from protobuf message tricked.EnvironmentConfig
 */
export interface EnvironmentConfig {
    /**
     * @generated from protobuf field: int32 difficulty = 1
     */
    difficulty: number;
    /**
     * @generated from protobuf field: int32 temp_decay_steps = 2
     */
    tempDecaySteps: number;
    /**
     * @generated from protobuf field: bool temp_boost = 3
     */
    tempBoost: boolean;
}
/**
 * @generated from protobuf message tricked.TrickedConfig
 */
export interface TrickedConfig {
    /**
     * @generated from protobuf field: string experiment_name_identifier = 1
     */
    experimentNameIdentifier: string;
    /**
     * @generated from protobuf field: int32 checkpoint_interval = 2
     */
    checkpointInterval: number;
    /**
     * @generated from protobuf field: tricked.HardwareConfig hardware = 3
     */
    hardware?: HardwareConfig;
    /**
     * @generated from protobuf field: tricked.ArchitectureConfig architecture = 4
     */
    architecture?: ArchitectureConfig;
    /**
     * @generated from protobuf field: tricked.OptimizerConfig optimizer = 5
     */
    optimizer?: OptimizerConfig;
    /**
     * @generated from protobuf field: tricked.MctsConfig mcts = 6
     */
    mcts?: MctsConfig;
    /**
     * @generated from protobuf field: tricked.EnvironmentConfig environment = 7
     */
    environment?: EnvironmentConfig;
}
/**
 * Hardware Metrics
 *
 * @generated from protobuf message tricked.HardwareMetrics
 */
export interface HardwareMetrics {
    /**
     * @generated from protobuf field: float cpu_usage = 1
     */
    cpuUsage: number;
    /**
     * @generated from protobuf field: repeated float cpu_cores_usage = 2
     */
    cpuCoresUsage: number[];
    /**
     * @generated from protobuf field: float ram_usage_pct = 3
     */
    ramUsagePct: number;
    /**
     * @generated from protobuf field: float ram_used_mb = 4
     */
    ramUsedMb: number;
    /**
     * @generated from protobuf field: float gpu_util = 5
     */
    gpuUtil: number;
    /**
     * @generated from protobuf field: float vram_used_mb = 6
     */
    vramUsedMb: number;
    /**
     * @generated from protobuf field: float disk_usage_pct = 7
     */
    diskUsagePct: number;
    /**
     * @generated from protobuf field: float network_rx_mbps = 8
     */
    networkRxMbps: number;
    /**
     * @generated from protobuf field: float network_tx_mbps = 9
     */
    networkTxMbps: number;
    /**
     * @generated from protobuf field: float disk_read_mbps = 10
     */
    diskReadMbps: number;
    /**
     * @generated from protobuf field: float disk_write_mbps = 11
     */
    diskWriteMbps: number;
    /**
     * @generated from protobuf field: string machine_identifier = 12
     */
    machineIdentifier: string;
}
/**
 * Full MetricRow structure
 *
 * @generated from protobuf message tricked.MetricRow
 */
export interface MetricRow {
    /**
     * @generated from protobuf field: string run_id = 1
     */
    runId: string;
    /**
     * @generated from protobuf field: int32 step = 2
     */
    step: number;
    /**
     * @generated from protobuf field: optional float total_loss = 3
     */
    totalLoss?: number;
    /**
     * @generated from protobuf field: optional float policy_loss = 4
     */
    policyLoss?: number;
    /**
     * @generated from protobuf field: optional float value_loss = 5
     */
    valueLoss?: number;
    /**
     * @generated from protobuf field: optional float reward_loss = 6
     */
    rewardLoss?: number;
    /**
     * @generated from protobuf field: optional float lr = 7
     */
    lr?: number;
    /**
     * @generated from protobuf field: optional float game_score_min = 8
     */
    gameScoreMin?: number;
    /**
     * @generated from protobuf field: optional float game_score_max = 9
     */
    gameScoreMax?: number;
    /**
     * @generated from protobuf field: optional float game_score_med = 10
     */
    gameScoreMed?: number;
    /**
     * @generated from protobuf field: optional float game_score_mean = 11
     */
    gameScoreMean?: number;
    /**
     * @generated from protobuf field: optional float win_rate = 12
     */
    winRate?: number;
    /**
     * @generated from protobuf field: optional float game_lines_cleared = 13
     */
    gameLinesCleared?: number;
    /**
     * @generated from protobuf field: optional float game_count = 14
     */
    gameCount?: number;
    /**
     * @generated from protobuf field: optional float ram_usage_mb = 15
     */
    ramUsageMb?: number;
    /**
     * @generated from protobuf field: optional float gpu_usage_pct = 16
     */
    gpuUsagePct?: number;
    /**
     * @generated from protobuf field: optional float cpu_usage_pct = 17
     */
    cpuUsagePct?: number;
    /**
     * @generated from protobuf field: optional float disk_usage_pct = 18
     */
    diskUsagePct?: number;
    /**
     * @generated from protobuf field: optional float vram_usage_mb = 19
     */
    vramUsageMb?: number;
    /**
     * @generated from protobuf field: optional float mcts_depth_mean = 20
     */
    mctsDepthMean?: number;
    /**
     * @generated from protobuf field: optional float mcts_search_time_mean = 21
     */
    mctsSearchTimeMean?: number;
    /**
     * @generated from protobuf field: optional float elapsed_time = 22
     */
    elapsedTime?: number;
    /**
     * @generated from protobuf field: optional float network_tx_mbps = 23
     */
    networkTxMbps?: number;
    /**
     * @generated from protobuf field: optional float network_rx_mbps = 24
     */
    networkRxMbps?: number;
    /**
     * @generated from protobuf field: optional float disk_read_mbps = 25
     */
    diskReadMbps?: number;
    /**
     * @generated from protobuf field: optional float disk_write_mbps = 26
     */
    diskWriteMbps?: number;
    /**
     * @generated from protobuf field: optional float policy_entropy = 27
     */
    policyEntropy?: number;
    /**
     * @generated from protobuf field: optional float gradient_norm = 28
     */
    gradientNorm?: number;
    /**
     * @generated from protobuf field: optional float representation_drift = 29
     */
    representationDrift?: number;
    /**
     * @generated from protobuf field: optional float mean_td_error = 30
     */
    meanTdError?: number;
    /**
     * @generated from protobuf field: optional float queue_saturation_ratio = 31
     */
    queueSaturationRatio?: number;
    /**
     * @generated from protobuf field: optional float sps_vs_tps = 32
     */
    spsVsTps?: number;
    /**
     * @generated from protobuf field: optional float queue_latency_us = 33
     */
    queueLatencyUs?: number;
    /**
     * @generated from protobuf field: optional float sumtree_contention_us = 34
     */
    sumtreeContentionUs?: number;
    /**
     * @generated from protobuf field: optional float action_space_entropy = 35
     */
    actionSpaceEntropy?: number;
    /**
     * @generated from protobuf field: optional string layer_gradient_norms = 36
     */
    layerGradientNorms?: string;
    /**
     * @generated from protobuf field: repeated float spatial_heatmap = 37
     */
    spatialHeatmap: number[];
    /**
     * @generated from protobuf field: optional float difficulty = 38
     */
    difficulty?: number;
}
/**
 * Complete Telemetry Payload encompassing everything
 *
 * @generated from protobuf message tricked.TelemetryPayload
 */
export interface TelemetryPayload {
    /**
     * @generated from protobuf field: tricked.HardwareMetrics hardware = 1
     */
    hardware?: HardwareMetrics;
    /**
     * @generated from protobuf field: tricked.MetricRow row = 2
     */
    row?: MetricRow;
}
/**
 * @generated from protobuf message tricked.MetricHistory
 */
export interface MetricHistory {
    /**
     * @generated from protobuf field: repeated tricked.MetricRow metrics = 1
     */
    metrics: MetricRow[];
}
// @generated message type with reflection information, may provide speed optimized methods
class HardwareConfig$Type extends MessageType<HardwareConfig> {
    constructor() {
        super("tricked.HardwareConfig", [
            { no: 1, name: "device", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "num_processes", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "worker_device", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "inference_batch_size_limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "inference_timeout_ms", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<HardwareConfig>): HardwareConfig {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.device = "";
        message.numProcesses = 0;
        message.workerDevice = "";
        message.inferenceBatchSizeLimit = 0;
        message.inferenceTimeoutMs = 0;
        if (value !== undefined)
            reflectionMergePartial<HardwareConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HardwareConfig): HardwareConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device */ 1:
                    message.device = reader.string();
                    break;
                case /* int32 num_processes */ 2:
                    message.numProcesses = reader.int32();
                    break;
                case /* string worker_device */ 3:
                    message.workerDevice = reader.string();
                    break;
                case /* int32 inference_batch_size_limit */ 4:
                    message.inferenceBatchSizeLimit = reader.int32();
                    break;
                case /* int32 inference_timeout_ms */ 5:
                    message.inferenceTimeoutMs = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HardwareConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device = 1; */
        if (message.device !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.device);
        /* int32 num_processes = 2; */
        if (message.numProcesses !== 0)
            writer.tag(2, WireType.Varint).int32(message.numProcesses);
        /* string worker_device = 3; */
        if (message.workerDevice !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.workerDevice);
        /* int32 inference_batch_size_limit = 4; */
        if (message.inferenceBatchSizeLimit !== 0)
            writer.tag(4, WireType.Varint).int32(message.inferenceBatchSizeLimit);
        /* int32 inference_timeout_ms = 5; */
        if (message.inferenceTimeoutMs !== 0)
            writer.tag(5, WireType.Varint).int32(message.inferenceTimeoutMs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tricked.HardwareConfig
 */
export const HardwareConfig = new HardwareConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ArchitectureConfig$Type extends MessageType<ArchitectureConfig> {
    constructor() {
        super("tricked.ArchitectureConfig", [
            { no: 1, name: "hidden_dimension_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "num_blocks", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "value_support_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "reward_support_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "spatial_channel_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "hole_predictor_dim", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ArchitectureConfig>): ArchitectureConfig {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.hiddenDimensionSize = 0;
        message.numBlocks = 0;
        message.valueSupportSize = 0;
        message.rewardSupportSize = 0;
        message.spatialChannelCount = 0;
        message.holePredictorDim = 0;
        if (value !== undefined)
            reflectionMergePartial<ArchitectureConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ArchitectureConfig): ArchitectureConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 hidden_dimension_size */ 1:
                    message.hiddenDimensionSize = reader.int32();
                    break;
                case /* int32 num_blocks */ 2:
                    message.numBlocks = reader.int32();
                    break;
                case /* int32 value_support_size */ 3:
                    message.valueSupportSize = reader.int32();
                    break;
                case /* int32 reward_support_size */ 4:
                    message.rewardSupportSize = reader.int32();
                    break;
                case /* int32 spatial_channel_count */ 5:
                    message.spatialChannelCount = reader.int32();
                    break;
                case /* int32 hole_predictor_dim */ 6:
                    message.holePredictorDim = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ArchitectureConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 hidden_dimension_size = 1; */
        if (message.hiddenDimensionSize !== 0)
            writer.tag(1, WireType.Varint).int32(message.hiddenDimensionSize);
        /* int32 num_blocks = 2; */
        if (message.numBlocks !== 0)
            writer.tag(2, WireType.Varint).int32(message.numBlocks);
        /* int32 value_support_size = 3; */
        if (message.valueSupportSize !== 0)
            writer.tag(3, WireType.Varint).int32(message.valueSupportSize);
        /* int32 reward_support_size = 4; */
        if (message.rewardSupportSize !== 0)
            writer.tag(4, WireType.Varint).int32(message.rewardSupportSize);
        /* int32 spatial_channel_count = 5; */
        if (message.spatialChannelCount !== 0)
            writer.tag(5, WireType.Varint).int32(message.spatialChannelCount);
        /* int32 hole_predictor_dim = 6; */
        if (message.holePredictorDim !== 0)
            writer.tag(6, WireType.Varint).int32(message.holePredictorDim);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tricked.ArchitectureConfig
 */
export const ArchitectureConfig = new ArchitectureConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OptimizerConfig$Type extends MessageType<OptimizerConfig> {
    constructor() {
        super("tricked.OptimizerConfig", [
            { no: 1, name: "buffer_capacity_limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "train_batch_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "discount_factor", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 4, name: "td_lambda", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 5, name: "weight_decay", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 6, name: "lr_init", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 7, name: "unroll_steps", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "temporal_difference_steps", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "reanalyze_ratio", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 10, name: "max_steps", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "prioritized_replay_alpha", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 12, name: "prioritized_replay_beta", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<OptimizerConfig>): OptimizerConfig {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.bufferCapacityLimit = 0;
        message.trainBatchSize = 0;
        message.discountFactor = 0;
        message.tdLambda = 0;
        message.weightDecay = 0;
        message.lrInit = 0;
        message.unrollSteps = 0;
        message.temporalDifferenceSteps = 0;
        message.reanalyzeRatio = 0;
        message.maxSteps = 0;
        if (value !== undefined)
            reflectionMergePartial<OptimizerConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OptimizerConfig): OptimizerConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 buffer_capacity_limit */ 1:
                    message.bufferCapacityLimit = reader.int32();
                    break;
                case /* int32 train_batch_size */ 2:
                    message.trainBatchSize = reader.int32();
                    break;
                case /* float discount_factor */ 3:
                    message.discountFactor = reader.float();
                    break;
                case /* float td_lambda */ 4:
                    message.tdLambda = reader.float();
                    break;
                case /* float weight_decay */ 5:
                    message.weightDecay = reader.float();
                    break;
                case /* float lr_init */ 6:
                    message.lrInit = reader.float();
                    break;
                case /* int32 unroll_steps */ 7:
                    message.unrollSteps = reader.int32();
                    break;
                case /* int32 temporal_difference_steps */ 8:
                    message.temporalDifferenceSteps = reader.int32();
                    break;
                case /* float reanalyze_ratio */ 9:
                    message.reanalyzeRatio = reader.float();
                    break;
                case /* int32 max_steps */ 10:
                    message.maxSteps = reader.int32();
                    break;
                case /* optional float prioritized_replay_alpha */ 11:
                    message.prioritizedReplayAlpha = reader.float();
                    break;
                case /* optional float prioritized_replay_beta */ 12:
                    message.prioritizedReplayBeta = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OptimizerConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 buffer_capacity_limit = 1; */
        if (message.bufferCapacityLimit !== 0)
            writer.tag(1, WireType.Varint).int32(message.bufferCapacityLimit);
        /* int32 train_batch_size = 2; */
        if (message.trainBatchSize !== 0)
            writer.tag(2, WireType.Varint).int32(message.trainBatchSize);
        /* float discount_factor = 3; */
        if (message.discountFactor !== 0)
            writer.tag(3, WireType.Bit32).float(message.discountFactor);
        /* float td_lambda = 4; */
        if (message.tdLambda !== 0)
            writer.tag(4, WireType.Bit32).float(message.tdLambda);
        /* float weight_decay = 5; */
        if (message.weightDecay !== 0)
            writer.tag(5, WireType.Bit32).float(message.weightDecay);
        /* float lr_init = 6; */
        if (message.lrInit !== 0)
            writer.tag(6, WireType.Bit32).float(message.lrInit);
        /* int32 unroll_steps = 7; */
        if (message.unrollSteps !== 0)
            writer.tag(7, WireType.Varint).int32(message.unrollSteps);
        /* int32 temporal_difference_steps = 8; */
        if (message.temporalDifferenceSteps !== 0)
            writer.tag(8, WireType.Varint).int32(message.temporalDifferenceSteps);
        /* float reanalyze_ratio = 9; */
        if (message.reanalyzeRatio !== 0)
            writer.tag(9, WireType.Bit32).float(message.reanalyzeRatio);
        /* int32 max_steps = 10; */
        if (message.maxSteps !== 0)
            writer.tag(10, WireType.Varint).int32(message.maxSteps);
        /* optional float prioritized_replay_alpha = 11; */
        if (message.prioritizedReplayAlpha !== undefined)
            writer.tag(11, WireType.Bit32).float(message.prioritizedReplayAlpha);
        /* optional float prioritized_replay_beta = 12; */
        if (message.prioritizedReplayBeta !== undefined)
            writer.tag(12, WireType.Bit32).float(message.prioritizedReplayBeta);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tricked.OptimizerConfig
 */
export const OptimizerConfig = new OptimizerConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MctsConfig$Type extends MessageType<MctsConfig> {
    constructor() {
        super("tricked.MctsConfig", [
            { no: 1, name: "simulations", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "max_gumbel_k", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "gumbel_scale", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<MctsConfig>): MctsConfig {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.simulations = 0;
        message.maxGumbelK = 0;
        message.gumbelScale = 0;
        if (value !== undefined)
            reflectionMergePartial<MctsConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MctsConfig): MctsConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 simulations */ 1:
                    message.simulations = reader.int32();
                    break;
                case /* int32 max_gumbel_k */ 2:
                    message.maxGumbelK = reader.int32();
                    break;
                case /* float gumbel_scale */ 3:
                    message.gumbelScale = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MctsConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 simulations = 1; */
        if (message.simulations !== 0)
            writer.tag(1, WireType.Varint).int32(message.simulations);
        /* int32 max_gumbel_k = 2; */
        if (message.maxGumbelK !== 0)
            writer.tag(2, WireType.Varint).int32(message.maxGumbelK);
        /* float gumbel_scale = 3; */
        if (message.gumbelScale !== 0)
            writer.tag(3, WireType.Bit32).float(message.gumbelScale);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tricked.MctsConfig
 */
export const MctsConfig = new MctsConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EnvironmentConfig$Type extends MessageType<EnvironmentConfig> {
    constructor() {
        super("tricked.EnvironmentConfig", [
            { no: 1, name: "difficulty", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "temp_decay_steps", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "temp_boost", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<EnvironmentConfig>): EnvironmentConfig {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.difficulty = 0;
        message.tempDecaySteps = 0;
        message.tempBoost = false;
        if (value !== undefined)
            reflectionMergePartial<EnvironmentConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnvironmentConfig): EnvironmentConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 difficulty */ 1:
                    message.difficulty = reader.int32();
                    break;
                case /* int32 temp_decay_steps */ 2:
                    message.tempDecaySteps = reader.int32();
                    break;
                case /* bool temp_boost */ 3:
                    message.tempBoost = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EnvironmentConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 difficulty = 1; */
        if (message.difficulty !== 0)
            writer.tag(1, WireType.Varint).int32(message.difficulty);
        /* int32 temp_decay_steps = 2; */
        if (message.tempDecaySteps !== 0)
            writer.tag(2, WireType.Varint).int32(message.tempDecaySteps);
        /* bool temp_boost = 3; */
        if (message.tempBoost !== false)
            writer.tag(3, WireType.Varint).bool(message.tempBoost);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tricked.EnvironmentConfig
 */
export const EnvironmentConfig = new EnvironmentConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TrickedConfig$Type extends MessageType<TrickedConfig> {
    constructor() {
        super("tricked.TrickedConfig", [
            { no: 1, name: "experiment_name_identifier", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "checkpoint_interval", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "hardware", kind: "message", T: () => HardwareConfig },
            { no: 4, name: "architecture", kind: "message", T: () => ArchitectureConfig },
            { no: 5, name: "optimizer", kind: "message", T: () => OptimizerConfig },
            { no: 6, name: "mcts", kind: "message", T: () => MctsConfig },
            { no: 7, name: "environment", kind: "message", T: () => EnvironmentConfig }
        ]);
    }
    create(value?: PartialMessage<TrickedConfig>): TrickedConfig {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.experimentNameIdentifier = "";
        message.checkpointInterval = 0;
        if (value !== undefined)
            reflectionMergePartial<TrickedConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TrickedConfig): TrickedConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string experiment_name_identifier */ 1:
                    message.experimentNameIdentifier = reader.string();
                    break;
                case /* int32 checkpoint_interval */ 2:
                    message.checkpointInterval = reader.int32();
                    break;
                case /* tricked.HardwareConfig hardware */ 3:
                    message.hardware = HardwareConfig.internalBinaryRead(reader, reader.uint32(), options, message.hardware);
                    break;
                case /* tricked.ArchitectureConfig architecture */ 4:
                    message.architecture = ArchitectureConfig.internalBinaryRead(reader, reader.uint32(), options, message.architecture);
                    break;
                case /* tricked.OptimizerConfig optimizer */ 5:
                    message.optimizer = OptimizerConfig.internalBinaryRead(reader, reader.uint32(), options, message.optimizer);
                    break;
                case /* tricked.MctsConfig mcts */ 6:
                    message.mcts = MctsConfig.internalBinaryRead(reader, reader.uint32(), options, message.mcts);
                    break;
                case /* tricked.EnvironmentConfig environment */ 7:
                    message.environment = EnvironmentConfig.internalBinaryRead(reader, reader.uint32(), options, message.environment);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TrickedConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string experiment_name_identifier = 1; */
        if (message.experimentNameIdentifier !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.experimentNameIdentifier);
        /* int32 checkpoint_interval = 2; */
        if (message.checkpointInterval !== 0)
            writer.tag(2, WireType.Varint).int32(message.checkpointInterval);
        /* tricked.HardwareConfig hardware = 3; */
        if (message.hardware)
            HardwareConfig.internalBinaryWrite(message.hardware, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* tricked.ArchitectureConfig architecture = 4; */
        if (message.architecture)
            ArchitectureConfig.internalBinaryWrite(message.architecture, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* tricked.OptimizerConfig optimizer = 5; */
        if (message.optimizer)
            OptimizerConfig.internalBinaryWrite(message.optimizer, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* tricked.MctsConfig mcts = 6; */
        if (message.mcts)
            MctsConfig.internalBinaryWrite(message.mcts, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* tricked.EnvironmentConfig environment = 7; */
        if (message.environment)
            EnvironmentConfig.internalBinaryWrite(message.environment, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tricked.TrickedConfig
 */
export const TrickedConfig = new TrickedConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HardwareMetrics$Type extends MessageType<HardwareMetrics> {
    constructor() {
        super("tricked.HardwareMetrics", [
            { no: 1, name: "cpu_usage", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 2, name: "cpu_cores_usage", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 2 /*ScalarType.FLOAT*/ },
            { no: 3, name: "ram_usage_pct", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 4, name: "ram_used_mb", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 5, name: "gpu_util", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 6, name: "vram_used_mb", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 7, name: "disk_usage_pct", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 8, name: "network_rx_mbps", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 9, name: "network_tx_mbps", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 10, name: "disk_read_mbps", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 11, name: "disk_write_mbps", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 12, name: "machine_identifier", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<HardwareMetrics>): HardwareMetrics {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cpuUsage = 0;
        message.cpuCoresUsage = [];
        message.ramUsagePct = 0;
        message.ramUsedMb = 0;
        message.gpuUtil = 0;
        message.vramUsedMb = 0;
        message.diskUsagePct = 0;
        message.networkRxMbps = 0;
        message.networkTxMbps = 0;
        message.diskReadMbps = 0;
        message.diskWriteMbps = 0;
        message.machineIdentifier = "";
        if (value !== undefined)
            reflectionMergePartial<HardwareMetrics>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HardwareMetrics): HardwareMetrics {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* float cpu_usage */ 1:
                    message.cpuUsage = reader.float();
                    break;
                case /* repeated float cpu_cores_usage */ 2:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.cpuCoresUsage.push(reader.float());
                    else
                        message.cpuCoresUsage.push(reader.float());
                    break;
                case /* float ram_usage_pct */ 3:
                    message.ramUsagePct = reader.float();
                    break;
                case /* float ram_used_mb */ 4:
                    message.ramUsedMb = reader.float();
                    break;
                case /* float gpu_util */ 5:
                    message.gpuUtil = reader.float();
                    break;
                case /* float vram_used_mb */ 6:
                    message.vramUsedMb = reader.float();
                    break;
                case /* float disk_usage_pct */ 7:
                    message.diskUsagePct = reader.float();
                    break;
                case /* float network_rx_mbps */ 8:
                    message.networkRxMbps = reader.float();
                    break;
                case /* float network_tx_mbps */ 9:
                    message.networkTxMbps = reader.float();
                    break;
                case /* float disk_read_mbps */ 10:
                    message.diskReadMbps = reader.float();
                    break;
                case /* float disk_write_mbps */ 11:
                    message.diskWriteMbps = reader.float();
                    break;
                case /* string machine_identifier */ 12:
                    message.machineIdentifier = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HardwareMetrics, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* float cpu_usage = 1; */
        if (message.cpuUsage !== 0)
            writer.tag(1, WireType.Bit32).float(message.cpuUsage);
        /* repeated float cpu_cores_usage = 2; */
        if (message.cpuCoresUsage.length) {
            writer.tag(2, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.cpuCoresUsage.length; i++)
                writer.float(message.cpuCoresUsage[i]);
            writer.join();
        }
        /* float ram_usage_pct = 3; */
        if (message.ramUsagePct !== 0)
            writer.tag(3, WireType.Bit32).float(message.ramUsagePct);
        /* float ram_used_mb = 4; */
        if (message.ramUsedMb !== 0)
            writer.tag(4, WireType.Bit32).float(message.ramUsedMb);
        /* float gpu_util = 5; */
        if (message.gpuUtil !== 0)
            writer.tag(5, WireType.Bit32).float(message.gpuUtil);
        /* float vram_used_mb = 6; */
        if (message.vramUsedMb !== 0)
            writer.tag(6, WireType.Bit32).float(message.vramUsedMb);
        /* float disk_usage_pct = 7; */
        if (message.diskUsagePct !== 0)
            writer.tag(7, WireType.Bit32).float(message.diskUsagePct);
        /* float network_rx_mbps = 8; */
        if (message.networkRxMbps !== 0)
            writer.tag(8, WireType.Bit32).float(message.networkRxMbps);
        /* float network_tx_mbps = 9; */
        if (message.networkTxMbps !== 0)
            writer.tag(9, WireType.Bit32).float(message.networkTxMbps);
        /* float disk_read_mbps = 10; */
        if (message.diskReadMbps !== 0)
            writer.tag(10, WireType.Bit32).float(message.diskReadMbps);
        /* float disk_write_mbps = 11; */
        if (message.diskWriteMbps !== 0)
            writer.tag(11, WireType.Bit32).float(message.diskWriteMbps);
        /* string machine_identifier = 12; */
        if (message.machineIdentifier !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.machineIdentifier);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tricked.HardwareMetrics
 */
export const HardwareMetrics = new HardwareMetrics$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MetricRow$Type extends MessageType<MetricRow> {
    constructor() {
        super("tricked.MetricRow", [
            { no: 1, name: "run_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "step", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "total_loss", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 4, name: "policy_loss", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 5, name: "value_loss", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 6, name: "reward_loss", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 7, name: "lr", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 8, name: "game_score_min", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 9, name: "game_score_max", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 10, name: "game_score_med", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 11, name: "game_score_mean", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 12, name: "win_rate", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 13, name: "game_lines_cleared", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 14, name: "game_count", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 15, name: "ram_usage_mb", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 16, name: "gpu_usage_pct", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 17, name: "cpu_usage_pct", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 18, name: "disk_usage_pct", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 19, name: "vram_usage_mb", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 20, name: "mcts_depth_mean", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 21, name: "mcts_search_time_mean", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 22, name: "elapsed_time", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 23, name: "network_tx_mbps", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 24, name: "network_rx_mbps", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 25, name: "disk_read_mbps", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 26, name: "disk_write_mbps", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 27, name: "policy_entropy", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 28, name: "gradient_norm", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 29, name: "representation_drift", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 30, name: "mean_td_error", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 31, name: "queue_saturation_ratio", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 32, name: "sps_vs_tps", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 33, name: "queue_latency_us", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 34, name: "sumtree_contention_us", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 35, name: "action_space_entropy", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ },
            { no: 36, name: "layer_gradient_norms", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 37, name: "spatial_heatmap", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 2 /*ScalarType.FLOAT*/ },
            { no: 38, name: "difficulty", kind: "scalar", opt: true, T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<MetricRow>): MetricRow {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.runId = "";
        message.step = 0;
        message.spatialHeatmap = [];
        if (value !== undefined)
            reflectionMergePartial<MetricRow>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MetricRow): MetricRow {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string run_id */ 1:
                    message.runId = reader.string();
                    break;
                case /* int32 step */ 2:
                    message.step = reader.int32();
                    break;
                case /* optional float total_loss */ 3:
                    message.totalLoss = reader.float();
                    break;
                case /* optional float policy_loss */ 4:
                    message.policyLoss = reader.float();
                    break;
                case /* optional float value_loss */ 5:
                    message.valueLoss = reader.float();
                    break;
                case /* optional float reward_loss */ 6:
                    message.rewardLoss = reader.float();
                    break;
                case /* optional float lr */ 7:
                    message.lr = reader.float();
                    break;
                case /* optional float game_score_min */ 8:
                    message.gameScoreMin = reader.float();
                    break;
                case /* optional float game_score_max */ 9:
                    message.gameScoreMax = reader.float();
                    break;
                case /* optional float game_score_med */ 10:
                    message.gameScoreMed = reader.float();
                    break;
                case /* optional float game_score_mean */ 11:
                    message.gameScoreMean = reader.float();
                    break;
                case /* optional float win_rate */ 12:
                    message.winRate = reader.float();
                    break;
                case /* optional float game_lines_cleared */ 13:
                    message.gameLinesCleared = reader.float();
                    break;
                case /* optional float game_count */ 14:
                    message.gameCount = reader.float();
                    break;
                case /* optional float ram_usage_mb */ 15:
                    message.ramUsageMb = reader.float();
                    break;
                case /* optional float gpu_usage_pct */ 16:
                    message.gpuUsagePct = reader.float();
                    break;
                case /* optional float cpu_usage_pct */ 17:
                    message.cpuUsagePct = reader.float();
                    break;
                case /* optional float disk_usage_pct */ 18:
                    message.diskUsagePct = reader.float();
                    break;
                case /* optional float vram_usage_mb */ 19:
                    message.vramUsageMb = reader.float();
                    break;
                case /* optional float mcts_depth_mean */ 20:
                    message.mctsDepthMean = reader.float();
                    break;
                case /* optional float mcts_search_time_mean */ 21:
                    message.mctsSearchTimeMean = reader.float();
                    break;
                case /* optional float elapsed_time */ 22:
                    message.elapsedTime = reader.float();
                    break;
                case /* optional float network_tx_mbps */ 23:
                    message.networkTxMbps = reader.float();
                    break;
                case /* optional float network_rx_mbps */ 24:
                    message.networkRxMbps = reader.float();
                    break;
                case /* optional float disk_read_mbps */ 25:
                    message.diskReadMbps = reader.float();
                    break;
                case /* optional float disk_write_mbps */ 26:
                    message.diskWriteMbps = reader.float();
                    break;
                case /* optional float policy_entropy */ 27:
                    message.policyEntropy = reader.float();
                    break;
                case /* optional float gradient_norm */ 28:
                    message.gradientNorm = reader.float();
                    break;
                case /* optional float representation_drift */ 29:
                    message.representationDrift = reader.float();
                    break;
                case /* optional float mean_td_error */ 30:
                    message.meanTdError = reader.float();
                    break;
                case /* optional float queue_saturation_ratio */ 31:
                    message.queueSaturationRatio = reader.float();
                    break;
                case /* optional float sps_vs_tps */ 32:
                    message.spsVsTps = reader.float();
                    break;
                case /* optional float queue_latency_us */ 33:
                    message.queueLatencyUs = reader.float();
                    break;
                case /* optional float sumtree_contention_us */ 34:
                    message.sumtreeContentionUs = reader.float();
                    break;
                case /* optional float action_space_entropy */ 35:
                    message.actionSpaceEntropy = reader.float();
                    break;
                case /* optional string layer_gradient_norms */ 36:
                    message.layerGradientNorms = reader.string();
                    break;
                case /* repeated float spatial_heatmap */ 37:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.spatialHeatmap.push(reader.float());
                    else
                        message.spatialHeatmap.push(reader.float());
                    break;
                case /* optional float difficulty */ 38:
                    message.difficulty = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MetricRow, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string run_id = 1; */
        if (message.runId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.runId);
        /* int32 step = 2; */
        if (message.step !== 0)
            writer.tag(2, WireType.Varint).int32(message.step);
        /* optional float total_loss = 3; */
        if (message.totalLoss !== undefined)
            writer.tag(3, WireType.Bit32).float(message.totalLoss);
        /* optional float policy_loss = 4; */
        if (message.policyLoss !== undefined)
            writer.tag(4, WireType.Bit32).float(message.policyLoss);
        /* optional float value_loss = 5; */
        if (message.valueLoss !== undefined)
            writer.tag(5, WireType.Bit32).float(message.valueLoss);
        /* optional float reward_loss = 6; */
        if (message.rewardLoss !== undefined)
            writer.tag(6, WireType.Bit32).float(message.rewardLoss);
        /* optional float lr = 7; */
        if (message.lr !== undefined)
            writer.tag(7, WireType.Bit32).float(message.lr);
        /* optional float game_score_min = 8; */
        if (message.gameScoreMin !== undefined)
            writer.tag(8, WireType.Bit32).float(message.gameScoreMin);
        /* optional float game_score_max = 9; */
        if (message.gameScoreMax !== undefined)
            writer.tag(9, WireType.Bit32).float(message.gameScoreMax);
        /* optional float game_score_med = 10; */
        if (message.gameScoreMed !== undefined)
            writer.tag(10, WireType.Bit32).float(message.gameScoreMed);
        /* optional float game_score_mean = 11; */
        if (message.gameScoreMean !== undefined)
            writer.tag(11, WireType.Bit32).float(message.gameScoreMean);
        /* optional float win_rate = 12; */
        if (message.winRate !== undefined)
            writer.tag(12, WireType.Bit32).float(message.winRate);
        /* optional float game_lines_cleared = 13; */
        if (message.gameLinesCleared !== undefined)
            writer.tag(13, WireType.Bit32).float(message.gameLinesCleared);
        /* optional float game_count = 14; */
        if (message.gameCount !== undefined)
            writer.tag(14, WireType.Bit32).float(message.gameCount);
        /* optional float ram_usage_mb = 15; */
        if (message.ramUsageMb !== undefined)
            writer.tag(15, WireType.Bit32).float(message.ramUsageMb);
        /* optional float gpu_usage_pct = 16; */
        if (message.gpuUsagePct !== undefined)
            writer.tag(16, WireType.Bit32).float(message.gpuUsagePct);
        /* optional float cpu_usage_pct = 17; */
        if (message.cpuUsagePct !== undefined)
            writer.tag(17, WireType.Bit32).float(message.cpuUsagePct);
        /* optional float disk_usage_pct = 18; */
        if (message.diskUsagePct !== undefined)
            writer.tag(18, WireType.Bit32).float(message.diskUsagePct);
        /* optional float vram_usage_mb = 19; */
        if (message.vramUsageMb !== undefined)
            writer.tag(19, WireType.Bit32).float(message.vramUsageMb);
        /* optional float mcts_depth_mean = 20; */
        if (message.mctsDepthMean !== undefined)
            writer.tag(20, WireType.Bit32).float(message.mctsDepthMean);
        /* optional float mcts_search_time_mean = 21; */
        if (message.mctsSearchTimeMean !== undefined)
            writer.tag(21, WireType.Bit32).float(message.mctsSearchTimeMean);
        /* optional float elapsed_time = 22; */
        if (message.elapsedTime !== undefined)
            writer.tag(22, WireType.Bit32).float(message.elapsedTime);
        /* optional float network_tx_mbps = 23; */
        if (message.networkTxMbps !== undefined)
            writer.tag(23, WireType.Bit32).float(message.networkTxMbps);
        /* optional float network_rx_mbps = 24; */
        if (message.networkRxMbps !== undefined)
            writer.tag(24, WireType.Bit32).float(message.networkRxMbps);
        /* optional float disk_read_mbps = 25; */
        if (message.diskReadMbps !== undefined)
            writer.tag(25, WireType.Bit32).float(message.diskReadMbps);
        /* optional float disk_write_mbps = 26; */
        if (message.diskWriteMbps !== undefined)
            writer.tag(26, WireType.Bit32).float(message.diskWriteMbps);
        /* optional float policy_entropy = 27; */
        if (message.policyEntropy !== undefined)
            writer.tag(27, WireType.Bit32).float(message.policyEntropy);
        /* optional float gradient_norm = 28; */
        if (message.gradientNorm !== undefined)
            writer.tag(28, WireType.Bit32).float(message.gradientNorm);
        /* optional float representation_drift = 29; */
        if (message.representationDrift !== undefined)
            writer.tag(29, WireType.Bit32).float(message.representationDrift);
        /* optional float mean_td_error = 30; */
        if (message.meanTdError !== undefined)
            writer.tag(30, WireType.Bit32).float(message.meanTdError);
        /* optional float queue_saturation_ratio = 31; */
        if (message.queueSaturationRatio !== undefined)
            writer.tag(31, WireType.Bit32).float(message.queueSaturationRatio);
        /* optional float sps_vs_tps = 32; */
        if (message.spsVsTps !== undefined)
            writer.tag(32, WireType.Bit32).float(message.spsVsTps);
        /* optional float queue_latency_us = 33; */
        if (message.queueLatencyUs !== undefined)
            writer.tag(33, WireType.Bit32).float(message.queueLatencyUs);
        /* optional float sumtree_contention_us = 34; */
        if (message.sumtreeContentionUs !== undefined)
            writer.tag(34, WireType.Bit32).float(message.sumtreeContentionUs);
        /* optional float action_space_entropy = 35; */
        if (message.actionSpaceEntropy !== undefined)
            writer.tag(35, WireType.Bit32).float(message.actionSpaceEntropy);
        /* optional string layer_gradient_norms = 36; */
        if (message.layerGradientNorms !== undefined)
            writer.tag(36, WireType.LengthDelimited).string(message.layerGradientNorms);
        /* repeated float spatial_heatmap = 37; */
        if (message.spatialHeatmap.length) {
            writer.tag(37, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.spatialHeatmap.length; i++)
                writer.float(message.spatialHeatmap[i]);
            writer.join();
        }
        /* optional float difficulty = 38; */
        if (message.difficulty !== undefined)
            writer.tag(38, WireType.Bit32).float(message.difficulty);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tricked.MetricRow
 */
export const MetricRow = new MetricRow$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TelemetryPayload$Type extends MessageType<TelemetryPayload> {
    constructor() {
        super("tricked.TelemetryPayload", [
            { no: 1, name: "hardware", kind: "message", T: () => HardwareMetrics },
            { no: 2, name: "row", kind: "message", T: () => MetricRow }
        ]);
    }
    create(value?: PartialMessage<TelemetryPayload>): TelemetryPayload {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<TelemetryPayload>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TelemetryPayload): TelemetryPayload {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* tricked.HardwareMetrics hardware */ 1:
                    message.hardware = HardwareMetrics.internalBinaryRead(reader, reader.uint32(), options, message.hardware);
                    break;
                case /* tricked.MetricRow row */ 2:
                    message.row = MetricRow.internalBinaryRead(reader, reader.uint32(), options, message.row);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TelemetryPayload, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* tricked.HardwareMetrics hardware = 1; */
        if (message.hardware)
            HardwareMetrics.internalBinaryWrite(message.hardware, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* tricked.MetricRow row = 2; */
        if (message.row)
            MetricRow.internalBinaryWrite(message.row, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tricked.TelemetryPayload
 */
export const TelemetryPayload = new TelemetryPayload$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MetricHistory$Type extends MessageType<MetricHistory> {
    constructor() {
        super("tricked.MetricHistory", [
            { no: 1, name: "metrics", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => MetricRow }
        ]);
    }
    create(value?: PartialMessage<MetricHistory>): MetricHistory {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.metrics = [];
        if (value !== undefined)
            reflectionMergePartial<MetricHistory>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MetricHistory): MetricHistory {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated tricked.MetricRow metrics */ 1:
                    message.metrics.push(MetricRow.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MetricHistory, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated tricked.MetricRow metrics = 1; */
        for (let i = 0; i < message.metrics.length; i++)
            MetricRow.internalBinaryWrite(message.metrics[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tricked.MetricHistory
 */
export const MetricHistory = new MetricHistory$Type();
