// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateRunApiRunsCreatePostData,
  CreateRunApiRunsCreatePostErrors,
  CreateRunApiRunsCreatePostResponses,
  DeleteRunApiRunsDeletePostData,
  DeleteRunApiRunsDeletePostErrors,
  DeleteRunApiRunsDeletePostResponses,
  FlushRunApiRunsFlushPostData,
  FlushRunApiRunsFlushPostErrors,
  FlushRunApiRunsFlushPostResponses,
  GetHardwareApiHardwareGetData,
  GetHardwareApiHardwareGetResponses,
  GetLogsApiRunsRunIdLogsGetData,
  GetLogsApiRunsRunIdLogsGetErrors,
  GetLogsApiRunsRunIdLogsGetResponses,
  GetMetricsApiRunsRunIdMetricsGetData,
  GetMetricsApiRunsRunIdMetricsGetErrors,
  GetMetricsApiRunsRunIdMetricsGetResponses,
  ListRunsApiRunsGetData,
  ListRunsApiRunsGetResponses,
  RenameRunApiRunsRenamePostData,
  RenameRunApiRunsRenamePostErrors,
  RenameRunApiRunsRenamePostResponses,
  SaveConfigApiRunsSaveConfigPostData,
  SaveConfigApiRunsSaveConfigPostErrors,
  SaveConfigApiRunsSaveConfigPostResponses,
  StartRunApiRunsStartPostData,
  StartRunApiRunsStartPostErrors,
  StartRunApiRunsStartPostResponses,
  StartStudyApiStudiesStartPostData,
  StartStudyApiStudiesStartPostErrors,
  StartStudyApiStudiesStartPostResponses,
  StopRunApiRunsStopPostData,
  StopRunApiRunsStopPostErrors,
  StopRunApiRunsStopPostResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Hardware
 */
export const getHardwareApiHardwareGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetHardwareApiHardwareGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetHardwareApiHardwareGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/hardware", ...options });

/**
 * List Runs
 */
export const listRunsApiRunsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListRunsApiRunsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListRunsApiRunsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/runs", ...options });

/**
 * Get Metrics
 */
export const getMetricsApiRunsRunIdMetricsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetMetricsApiRunsRunIdMetricsGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetMetricsApiRunsRunIdMetricsGetResponses,
    GetMetricsApiRunsRunIdMetricsGetErrors,
    ThrowOnError
  >({ url: "/api/runs/{run_id}/metrics", ...options });

/**
 * Get Logs
 */
export const getLogsApiRunsRunIdLogsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetLogsApiRunsRunIdLogsGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetLogsApiRunsRunIdLogsGetResponses,
    GetLogsApiRunsRunIdLogsGetErrors,
    ThrowOnError
  >({ url: "/api/runs/{run_id}/logs", ...options });

/**
 * Start Run
 */
export const startRunApiRunsStartPost = <ThrowOnError extends boolean = false>(
  options: Options<StartRunApiRunsStartPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StartRunApiRunsStartPostResponses,
    StartRunApiRunsStartPostErrors,
    ThrowOnError
  >({
    url: "/api/runs/start",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Start Study
 */
export const startStudyApiStudiesStartPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<StartStudyApiStudiesStartPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StartStudyApiStudiesStartPostResponses,
    StartStudyApiStudiesStartPostErrors,
    ThrowOnError
  >({
    url: "/api/studies/start",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Stop Run
 */
export const stopRunApiRunsStopPost = <ThrowOnError extends boolean = false>(
  options: Options<StopRunApiRunsStopPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StopRunApiRunsStopPostResponses,
    StopRunApiRunsStopPostErrors,
    ThrowOnError
  >({
    url: "/api/runs/stop",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Rename Run
 */
export const renameRunApiRunsRenamePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RenameRunApiRunsRenamePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RenameRunApiRunsRenamePostResponses,
    RenameRunApiRunsRenamePostErrors,
    ThrowOnError
  >({
    url: "/api/runs/rename",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Run
 */
export const deleteRunApiRunsDeletePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteRunApiRunsDeletePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    DeleteRunApiRunsDeletePostResponses,
    DeleteRunApiRunsDeletePostErrors,
    ThrowOnError
  >({
    url: "/api/runs/delete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Flush Run
 */
export const flushRunApiRunsFlushPost = <ThrowOnError extends boolean = false>(
  options: Options<FlushRunApiRunsFlushPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    FlushRunApiRunsFlushPostResponses,
    FlushRunApiRunsFlushPostErrors,
    ThrowOnError
  >({
    url: "/api/runs/flush",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Run
 */
export const createRunApiRunsCreatePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateRunApiRunsCreatePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateRunApiRunsCreatePostResponses,
    CreateRunApiRunsCreatePostErrors,
    ThrowOnError
  >({
    url: "/api/runs/create",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Save Config
 */
export const saveConfigApiRunsSaveConfigPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SaveConfigApiRunsSaveConfigPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SaveConfigApiRunsSaveConfigPostResponses,
    SaveConfigApiRunsSaveConfigPostErrors,
    ThrowOnError
  >({
    url: "/api/runs/save_config",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
