// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://127.0.0.1:8000" | (string & {});
};

/**
 * CreateRunReqBasic
 */
export type CreateRunReqBasic = {
  /**
   * Name
   */
  name: string;
  /**
   * Type
   */
  type: string;
  /**
   * Preset
   */
  preset?: string;
};

/**
 * DeleteRunReq
 */
export type DeleteRunReq = {
  /**
   * Id
   */
  id: string;
};

/**
 * FlushRunReq
 */
export type FlushRunReq = {
  /**
   * Id
   */
  id: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HardwareTelemetry
 */
export type HardwareTelemetry = {
  /**
   * Cpu Usage
   */
  cpu_usage: number;
  /**
   * Cpu Cores Usage
   */
  cpu_cores_usage: Array<number>;
  /**
   * Ram Usage Pct
   */
  ram_usage_pct: number;
  /**
   * Ram Used Mb
   */
  ram_used_mb: number;
  /**
   * Gpu Util
   */
  gpu_util: number;
  /**
   * Vram Used Mb
   */
  vram_used_mb: number;
  /**
   * Disk Usage Pct
   */
  disk_usage_pct: number;
  /**
   * Network Rx Mbps
   */
  network_rx_mbps: number;
  /**
   * Network Tx Mbps
   */
  network_tx_mbps: number;
  /**
   * Disk Read Mbps
   */
  disk_read_mbps: number;
  /**
   * Disk Write Mbps
   */
  disk_write_mbps: number;
  /**
   * Machine Identifier
   */
  machine_identifier: string;
};

/**
 * RenameRunReq
 */
export type RenameRunReq = {
  /**
   * Id
   */
  id: string;
  /**
   * Newname
   */
  newName: string;
};

/**
 * SaveConfigReq
 */
export type SaveConfigReq = {
  /**
   * Id
   */
  id: string;
  /**
   * Config
   */
  config: string;
};

/**
 * StartRunReq
 */
export type StartRunReq = {
  /**
   * Id
   */
  id: string;
};

/**
 * StartStudyReq
 */
export type StartStudyReq = {
  /**
   * Id
   */
  id: string;
};

/**
 * StopRunReq
 */
export type StopRunReq = {
  /**
   * Id
   */
  id: string;
  /**
   * Force
   */
  force?: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type GetHardwareApiHardwareGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/hardware";
};

export type GetHardwareApiHardwareGetResponses = {
  /**
   * Successful Response
   */
  200: HardwareTelemetry;
};

export type GetHardwareApiHardwareGetResponse =
  GetHardwareApiHardwareGetResponses[keyof GetHardwareApiHardwareGetResponses];

export type ListRunsApiRunsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/runs";
};

export type ListRunsApiRunsGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetMetricsApiRunsRunIdMetricsGetData = {
  body?: never;
  path: {
    /**
     * Run Id
     */
    run_id: string;
  };
  query?: never;
  url: "/api/runs/{run_id}/metrics";
};

export type GetMetricsApiRunsRunIdMetricsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMetricsApiRunsRunIdMetricsGetError =
  GetMetricsApiRunsRunIdMetricsGetErrors[keyof GetMetricsApiRunsRunIdMetricsGetErrors];

export type GetMetricsApiRunsRunIdMetricsGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetLogsApiRunsRunIdLogsGetData = {
  body?: never;
  path: {
    /**
     * Run Id
     */
    run_id: string;
  };
  query?: never;
  url: "/api/runs/{run_id}/logs";
};

export type GetLogsApiRunsRunIdLogsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLogsApiRunsRunIdLogsGetError =
  GetLogsApiRunsRunIdLogsGetErrors[keyof GetLogsApiRunsRunIdLogsGetErrors];

export type GetLogsApiRunsRunIdLogsGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type StartRunApiRunsStartPostData = {
  body: StartRunReq;
  path?: never;
  query?: never;
  url: "/api/runs/start";
};

export type StartRunApiRunsStartPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StartRunApiRunsStartPostError =
  StartRunApiRunsStartPostErrors[keyof StartRunApiRunsStartPostErrors];

export type StartRunApiRunsStartPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type StartStudyApiStudiesStartPostData = {
  body: StartStudyReq;
  path?: never;
  query?: never;
  url: "/api/studies/start";
};

export type StartStudyApiStudiesStartPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StartStudyApiStudiesStartPostError =
  StartStudyApiStudiesStartPostErrors[keyof StartStudyApiStudiesStartPostErrors];

export type StartStudyApiStudiesStartPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type StopRunApiRunsStopPostData = {
  body: StopRunReq;
  path?: never;
  query?: never;
  url: "/api/runs/stop";
};

export type StopRunApiRunsStopPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StopRunApiRunsStopPostError =
  StopRunApiRunsStopPostErrors[keyof StopRunApiRunsStopPostErrors];

export type StopRunApiRunsStopPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RenameRunApiRunsRenamePostData = {
  body: RenameRunReq;
  path?: never;
  query?: never;
  url: "/api/runs/rename";
};

export type RenameRunApiRunsRenamePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RenameRunApiRunsRenamePostError =
  RenameRunApiRunsRenamePostErrors[keyof RenameRunApiRunsRenamePostErrors];

export type RenameRunApiRunsRenamePostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteRunApiRunsDeletePostData = {
  body: DeleteRunReq;
  path?: never;
  query?: never;
  url: "/api/runs/delete";
};

export type DeleteRunApiRunsDeletePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteRunApiRunsDeletePostError =
  DeleteRunApiRunsDeletePostErrors[keyof DeleteRunApiRunsDeletePostErrors];

export type DeleteRunApiRunsDeletePostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type FlushRunApiRunsFlushPostData = {
  body: FlushRunReq;
  path?: never;
  query?: never;
  url: "/api/runs/flush";
};

export type FlushRunApiRunsFlushPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type FlushRunApiRunsFlushPostError =
  FlushRunApiRunsFlushPostErrors[keyof FlushRunApiRunsFlushPostErrors];

export type FlushRunApiRunsFlushPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CreateRunApiRunsCreatePostData = {
  body: CreateRunReqBasic;
  path?: never;
  query?: never;
  url: "/api/runs/create";
};

export type CreateRunApiRunsCreatePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateRunApiRunsCreatePostError =
  CreateRunApiRunsCreatePostErrors[keyof CreateRunApiRunsCreatePostErrors];

export type CreateRunApiRunsCreatePostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type SaveConfigApiRunsSaveConfigPostData = {
  body: SaveConfigReq;
  path?: never;
  query?: never;
  url: "/api/runs/save_config";
};

export type SaveConfigApiRunsSaveConfigPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SaveConfigApiRunsSaveConfigPostError =
  SaveConfigApiRunsSaveConfigPostErrors[keyof SaveConfigApiRunsSaveConfigPostErrors];

export type SaveConfigApiRunsSaveConfigPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
