// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessInfo } from "./ProcessInfo";

export type ActiveJob = {
  id: string;
  name: string;
  job_type: string;
  root_process: ProcessInfo | null;
};
