// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HardwareMetrics = {
  cpu_usage: number;
  cpu_cores_usage: Array<number> | null;
  ram_usage_pct: number;
  ram_used_mb: number;
  gpu_util: number;
  vram_used_mb: number;
  disk_usage_pct: number;
  network_rx_mbps: number;
  network_tx_mbps: number;
  disk_read_mbps: number;
  disk_write_mbps: number;
  machine_identifier: string;
};
