// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaygroundState = { board_low: string, board_high: string, available: [number, number, number], score: number, pieces_left: number, terminal: boolean, difficulty: number, lines_cleared: number, };
