// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Run = {
  id: string;
  name: string;
  type: string;
  status: string;
  config: string;
  start_time: string;
  tag: string | null;
};
