// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TelemetryData = {
  run_id: string;
  step: number;
  total_loss: number;
  policy_loss: number;
  value_loss: number;
  reward_loss: number;
  lr: number;
  game_score_min: number;
  game_score_max: number;
  game_score_med: number;
  game_score_mean: number;
  winrate_mean: number;
  game_lines_cleared: number;
  game_count: number;
  ram_usage_mb: number;
  gpu_usage_pct: number;
  cpu_usage_pct: number;
  io_usage: number;
  disk_usage_pct: number;
  vram_usage_mb: number;
  mcts_depth_mean: number;
  mcts_search_time_mean: number;
  network_tx_mbps: number;
  network_rx_mbps: number;
  disk_read_mbps: number;
  disk_write_mbps: number;
  policy_entropy: number;
  gradient_norm: number;
  representation_drift: number;
  mean_td_error: number;
  queue_saturation_ratio: number;
  sps_vs_tps: number;
  spatial_heatmap: Array<number>;
};
