// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrialData = { number: bigint, state: string, value: Array<number>, params: Record<string, any>, intermediate_values: Record<string, any>, };
