"""
Standard Documentation for node.py.

This module supplies the core execution logic for the `mcts` namespace, heavily typed and tested for production distribution.
"""

from __future__ import annotations

import math

import torch


class LatentNode:
    """
    MuZero Latent Tree Node.
    Instead of containing a real explicit board state (bitboards),
    it contains the `h` vector generated by the Representation/Dynamics network.
    """

    def __init__(self, prior: float, hidden_state: torch.Tensor | None = None):
        self.visits = 0
        self.value_sum = 0.0
        self.prior = prior
        self.hidden_state = hidden_state
        self.reward = 0.0
        self.gumbel_noise = 0.0

        self.children: dict[int, LatentNode] = {}
        self.is_expanded = False

    @property
    def value(self) -> float:
        if self.visits == 0:
            return 0.0
        return self.value_sum / self.visits

    def expand(self, hidden_state: torch.Tensor, reward: float, policy_probs: list[float]) -> None:
        """
        Expands the latent node using predictions from the neural network.
        - hidden_state: 'h' from the network
        - reward: 'r' predicted by Dynamics
        - policy_probs: 'p' predicted by Prediction (288 actions)
        """
        self.hidden_state = hidden_state
        self.reward = reward
        self.is_expanded = True

        # Instantiate children for all valid actions (indexed 0 to 149)
        for act_idx, prob in enumerate(policy_probs):
            if prob > 0:
                self.children[act_idx] = LatentNode(prior=prob)

    def select_child(self, is_root: bool = False) -> tuple[int, LatentNode | None]:
        """
        PUCT selection for latent tree, overridden by Gumbel Logic at the Root node.
        """
        best_score = -float("inf")
        best_action = -1
        best_child = None

        c1 = 1.25
        c2 = 19652
        explore_base = math.log((self.visits + c2 + 1) / c2) + c1

        for action, child in self.children.items():
            if child.visits == 0:
                q_value = self.value
            else:
                q_value = child.value

            if is_root:
                # Gumbel MuZero Score evaluates physical Logit space explicitly at the root level
                logit = math.log(max(child.prior, 1e-8))
                gumbel_logit = logit + child.gumbel_noise

                # Dynamic scaling to balance wide Point ranges (e.g. 50-100) vs strict logit depths
                c_scale = 50.0 / (child.visits + 1)
                score = gumbel_logit + (c_scale * q_value)
            else:
                # Standard AlphaZero internal exploration
                explore = explore_base * child.prior * (math.sqrt(self.visits) / (1 + child.visits))
                score = q_value + explore

            if score > best_score:
                best_score = score
                best_action = action
                best_child = child

        if best_child is None:
            return -1, None  # pragma: no cover

        return best_action, best_child
