"""
Script to discover all canonical piece shapes closed under D12 symmetry on the triangular grid.
This generates `src/tricked/env/piece_defs.py` which contains the mathematical coordinate offsets
used to build the piece bitmasks in `pieces.py`.
"""

import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
from typing import Any

from tricked.env.pieces import INDEX_TO_COORD, STANDARD_PIECES
from tricked.symmetry import D12_PERMUTATIONS


def normalize_shape(bitmask: int) -> Any:
    """
    Given a bitmask of a shape on the board, returns canonical offsets.
    The canonical anchor is the topmost, then leftmost coordinate.
    """
    
    coords = []
    for i in range(96):
        if (bitmask & (1 << i)) != 0:
            coords.append(INDEX_TO_COORD[i])

    if not coords:
        return None, None

    anchor = min(coords, key=lambda c: (c[1], c[0], c[2]))

    ax, ay, az = anchor

    offsets = []
    for cx, cy, cz in coords:
        offsets.append((int(cx - ax), int(cy - ay), int(cz - az)))

    offsets.sort()
    
    parity = anchor[2]
    return tuple(offsets), parity == 1

def generate_closed_piece_set() -> None:
    unique_shapes = set()

    for p_id in range(12):
        for t_idx, perm in enumerate(D12_PERMUTATIONS):
            
            for i in range(96):
                m = STANDARD_PIECES[p_id][i]
                if m == 0:
                    continue

                nm = 0
                for bit in range(96):
                    if (m & (1 << bit)) != 0:
                        nm |= 1 << perm[bit]

                offsets, anchor_is_up = normalize_shape(nm)
                if offsets:
                    unique_shapes.add((anchor_is_up, offsets))

    print(f"Discovered {len(unique_shapes)} unique canonical shapes under D12 closure.")

    out_lines = [
        '"""',
        "Auto-generated by src/tricked/closed_pieces.py.",
        "Contains the canonical D12-closed piece shapes as tuples of offsets.",
        '"""',
        "from typing import Any",
        "",
        "class PieceDef:",
        "    def __init__(self, require_up: bool, require_down: bool, offsets: list[tuple[int, int, int]]):",
        "        self.require_up = require_up",
        "        self.require_down = require_down",
        "        self.offsets = offsets",
        "",
        "PIECE_DEFS = [",
    ]

    for anchor_is_up, offsets in sorted(list(unique_shapes)):
        req_up = anchor_is_up
        req_down = not anchor_is_up
        out_lines.append(f"    PieceDef({req_up}, {req_down}, {list(offsets)}),")
    out_lines.append("]")
    out_lines.append("")

    out_path = os.path.join(os.path.dirname(__file__), "env", "piece_defs.py")
    with open(out_path, "w") as f:
        f.write("\n".join(out_lines))

    print(f"Successfully wrote {len(unique_shapes)} piece definitions to {out_path}")

if __name__ == "__main__":
    generate_closed_piece_set()
